"""Render an imaging report (X-ray, MRI): the centre's header, the patient, the image with its credit, findings,
impression and the radiologist's signature. The images are openly licensed (data/imaging/README.md)."""

from __future__ import annotations

import io
import random
from dataclasses import dataclass
from datetime import date
from pathlib import Path

from reportlab.graphics.barcode.code128 import Code128
from reportlab.lib.colors import Color, HexColor, black, white
from reportlab.lib.pagesizes import A4
from reportlab.lib.utils import ImageReader, simpleSplit
from reportlab.pdfgen.canvas import Canvas

W, H = A4
LEFT, RIGHT, TOP = 40, W - 40, H - 40
GREY = Color(0.45, 0.45, 0.45)
FOOTER = "Synthetic report generated by Nabz for software testing. Not a medical record."


@dataclass
class ImagingCentre:
    name: str
    address: str
    email: str
    radiologist: str
    colour: str = "#4b2e83"
    tagline: str = "Digital X-ray · MRI · CT · Ultrasound"


@dataclass
class ImagingSpec:
    centre: ImagingCentre
    patient_name: str
    age: int
    sex: str
    referrer: str
    when: date
    study_no: str
    title: str  # "X-RAY LEFT KNEE (AP VIEW)"
    history: str
    technique: str
    findings: list[str]
    impression: list[str]
    image: Path
    credit: str  # "Image: James Heilman, MD · CC BY-SA 4.0 · Wikimedia Commons"


def _paragraph(c: Canvas, text: str, x: float, y: float, width: float, font: str = "Helvetica", size: float = 9,
               leading: float = 12) -> float:
    c.setFont(font, size)
    for line in simpleSplit(text, font, size, width):
        c.drawString(x, y, line)
        y -= leading
    return y


def render_imaging_pdf(spec: ImagingSpec, out: Path | io.BytesIO) -> None:
    c = Canvas(out if isinstance(out, io.BytesIO) else str(out), pagesize=A4)
    c.setTitle(f"{spec.centre.name} - {spec.title.title()} - {spec.patient_name}")
    c.setAuthor(spec.centre.name)
    brand = HexColor(spec.centre.colour)
    rng = random.Random(spec.study_no)

    # header: a drawn mark, the centre, contact, a barcode for the study number
    c.setFillColor(brand)
    c.roundRect(LEFT, TOP - 32, 30, 30, 6, stroke=0, fill=1)
    c.setStrokeColor(white)
    c.setLineWidth(2)
    c.circle(LEFT + 15, TOP - 17, 8, stroke=1, fill=0)
    c.line(LEFT + 15, TOP - 29, LEFT + 15, TOP - 5)
    c.setFont("Helvetica-Bold", 16)
    c.drawString(LEFT + 38, TOP - 12, spec.centre.name)
    c.setFillColor(black)
    c.setFont("Helvetica-Oblique", 7.5)
    c.drawString(LEFT + 38, TOP - 22, spec.centre.tagline)
    c.setFont("Helvetica", 7.5)
    c.drawString(LEFT + 38, TOP - 31, f"{spec.centre.address}  |  {spec.centre.email}")
    barcode = Code128(spec.study_no, barHeight=22, barWidth=0.9, humanReadable=False)
    barcode.drawOn(c, RIGHT - barcode.width, TOP - 30)
    c.setStrokeColor(brand)
    c.setLineWidth(1.4)
    c.line(LEFT, TOP - 40, RIGHT, TOP - 40)
    c.setLineWidth(1)

    when = spec.when.strftime("%d/%m/%Y")
    fields = [
        ("Patient Name", spec.patient_name, "Study No.", spec.study_no),
        ("Age / Sex", f"{spec.age} Y / {spec.sex.title()}", "Study Date",
         f"{when} {rng.randint(9, 16):02d}:{rng.randint(10, 55):02d}"),
        ("Ref. By", spec.referrer, "Reported", f"{when} {rng.randint(17, 20):02d}:{rng.randint(10, 55):02d}"),
    ]
    y = TOP - 58
    c.setStrokeColor(Color(0.75, 0.75, 0.75))
    c.roundRect(LEFT, y - 30, RIGHT - LEFT, 45, 3, stroke=1, fill=0)
    c.setStrokeColor(black)
    for a, av, b, bv in fields:
        c.setFont("Helvetica-Bold", 8.5)
        c.drawString(LEFT + 6, y, f"{a}:")
        c.drawString(W / 2 + 20, y, f"{b}:")
        c.setFont("Helvetica", 8.5)
        c.drawString(LEFT + 80, y, av)
        c.drawString(W / 2 + 90, y, bv)
        y -= 13

    c.setFont("Helvetica-Bold", 12)
    c.drawCentredString(W / 2, y - 14, spec.title)
    y -= 34

    # the image on a black film, scaled to fit, with its credit underneath
    img = ImageReader(str(spec.image))
    iw, ih = img.getSize()
    box_w, box_h = RIGHT - LEFT - 120, 300
    scale = min(box_w / iw, box_h / ih)
    dw, dh = iw * scale, ih * scale
    fx = (W - dw) / 2
    c.setFillColor(black)
    c.rect(fx - 6, y - dh - 6, dw + 12, dh + 12, stroke=0, fill=1)
    c.drawImage(img, fx, y - dh, dw, dh)
    y -= dh + 16
    c.setFillColor(GREY)
    c.setFont("Helvetica", 6.5)
    c.drawCentredString(W / 2, y, spec.credit)
    c.setFillColor(black)
    y -= 18

    width = RIGHT - LEFT
    for label, text in (("Clinical history", spec.history), ("Technique", spec.technique)):
        c.setFont("Helvetica-Bold", 9)
        c.drawString(LEFT, y, f"{label}:")
        y = _paragraph(c, text, LEFT + 90, y, width - 90)
        y -= 4
    c.setFont("Helvetica-Bold", 10)
    c.drawString(LEFT, y - 4, "FINDINGS")
    y -= 18
    for f in spec.findings:
        c.setFont("Helvetica", 9)
        c.drawString(LEFT + 4, y, "•")
        y = _paragraph(c, f, LEFT + 14, y, width - 14)
        y -= 2
    c.setFont("Helvetica-Bold", 10)
    c.drawString(LEFT, y - 6, "IMPRESSION")
    y -= 20
    for f in spec.impression:
        c.setFont("Helvetica-Bold", 9)
        c.drawString(LEFT + 4, y, "•")
        y = _paragraph(c, f, LEFT + 14, y, width - 14, font="Helvetica-Bold")
        y -= 2

    # signature
    y = max(y - 30, 90)
    sig = random.Random(spec.centre.radiologist)
    c.setStrokeColor(HexColor("#1b2a6b"))
    c.setLineWidth(0.9)
    path = c.beginPath()
    px, py = RIGHT - 120, y + 14
    path.moveTo(px, py)
    for _ in range(5):
        nx = px + 18
        path.curveTo(px + sig.uniform(2, 8), py + sig.uniform(6, 14), nx - sig.uniform(2, 8), py - sig.uniform(4, 10),
                     nx, py + sig.uniform(-3, 3))
        px = nx
    c.drawPath(path, stroke=1, fill=0)
    c.setStrokeColor(black)
    c.setFont("Helvetica-Bold", 8.5)
    c.drawRightString(RIGHT, y, f"{spec.centre.radiologist}, MD (Radiodiagnosis)")
    c.setFont("Helvetica", 7.5)
    c.drawRightString(RIGHT, y - 10, "Consultant Radiologist")

    c.setStrokeColor(brand)
    c.line(LEFT, 52, RIGHT, 52)
    c.setFont("Helvetica", 7)
    c.setFillColor(GREY)
    c.drawString(LEFT, 43, "This report is a professional opinion and should be correlated clinically.")
    c.drawRightString(RIGHT, 43, "Page 1 of 1")
    c.setFont("Helvetica-Oblique", 6)
    c.drawString(LEFT, 33, FOOTER)
    c.save()
