"""Render a ReportSpec to PDF with one of three layouts, recording each row's bounding box."""

from __future__ import annotations

from pathlib import Path

from reportlab.lib.colors import Color, black
from reportlab.lib.pagesizes import A4
from reportlab.pdfbase.pdfmetrics import stringWidth
from reportlab.pdfgen.canvas import Canvas

from tools.synthetic.spec import ReportSpec, Row

W, H = A4
LEFT, RIGHT, TOP, BOTTOM = 40, W - 40, H - 40, 70
GREY = Color(0.55, 0.55, 0.55)
LIGHT = Color(0.92, 0.92, 0.92)
FOOTER = "SYNTHETIC REPORT generated by Nabz for software testing. Not a medical record."


class _Doc:
    def __init__(self, spec: ReportSpec, path: Path):
        self.spec = spec
        self.c = Canvas(str(path), pagesize=A4)
        self.c.setTitle(f"Synthetic lab report {spec.id}")
        self.page = 0
        self.y = 0.0

    # -- page furniture ---------------------------------------------------------------
    def header(self) -> None:
        s, c = self.spec, self.c
        if self.page == 0:
            c.setFont("Helvetica-Bold", 16)
            c.drawString(LEFT, TOP - 4, s.lab.name)
            c.setFont("Helvetica", 8.5)
            c.drawString(LEFT, TOP - 18, s.lab.address)
            c.line(LEFT, TOP - 26, RIGHT, TOP - 26)
            p = s.persona
            fields = [
                ("Patient Name", s.patient_name, "Lab No.", s.lab_no),
                ("Age / Sex", f"{p.age} Y / {p.sex.title()}", "Collected", s.collected_at.strftime("%d/%m/%Y 08:15")),
                ("Ref. By", s.lab.doctor, "Reported", s.collected_at.strftime("%d/%m/%Y 17:40")),
            ]
            y = TOP - 42
            for a, av, b, bv in fields:
                c.setFont("Helvetica-Bold", 9)
                c.drawString(LEFT, y, f"{a}:")
                c.drawString(W / 2 + 20, y, f"{b}:")
                c.setFont("Helvetica", 9)
                c.drawString(LEFT + 80, y, av)
                c.drawString(W / 2 + 90, y, bv)
                y -= 13
            c.line(LEFT, y + 4, RIGHT, y + 4)
            c.setFont("Helvetica-Bold", 11)
            c.drawCentredString(W / 2, y - 12, s.package.upper())
            self.y = y - 34
        else:
            c.setFont("Helvetica-Bold", 10)
            c.drawString(LEFT, TOP - 4, s.lab.name)
            c.setFont("Helvetica", 8.5)
            c.drawRightString(RIGHT, TOP - 4, f"{s.patient_name} · Lab No. {s.lab_no}")
            c.line(LEFT, TOP - 10, RIGHT, TOP - 10)
            self.y = TOP - 30

    def footer(self) -> None:
        c = self.c
        c.setFont("Helvetica-Oblique", 7.5)
        c.setFillColor(GREY)
        c.drawString(LEFT, 40, FOOTER)
        c.drawRightString(RIGHT, 40, f"Page {self.page + 1}")
        c.setFillColor(black)

    def new_page(self) -> None:
        if self.page or self.y:
            self.footer()
            self.c.showPage()
            self.page += 1
        self.header()

    def ensure(self, height: float) -> None:
        if self.y - height < BOTTOM:
            self.new_page()

    def record(self, row: Row, y: float, x0: float = LEFT, x1: float = RIGHT) -> None:
        row.page = self.page
        row.bbox = (round(x0, 1), round(H - (y + 9), 1), round(x1, 1), round(H - (y - 3), 1))

    def finish(self) -> int:
        c = self.c
        self.ensure(60)
        c.setFont("Helvetica", 8.5)
        c.drawCentredString(W / 2, self.y - 6, "--- End of report ---")
        c.setFont("Helvetica-Bold", 9)
        c.drawRightString(RIGHT, self.y - 36, f"{self.spec.lab.doctor}, MD (Pathology)")
        self.footer()
        c.save()
        return self.page + 1


def _layout_table(d: _Doc) -> None:
    cols = (LEFT + 4, 250, 312, 340, 440)
    c = d.c
    for section in d.spec.sections:
        d.ensure(60)
        c.setFillColor(LIGHT)
        c.rect(LEFT, d.y - 4, RIGHT - LEFT, 15, stroke=0, fill=1)
        c.setFillColor(black)
        c.setFont("Helvetica-Bold", 9.5)
        c.drawString(LEFT + 4, d.y, section.title)
        d.y -= 18
        c.setFont("Helvetica-Bold", 8.5)
        for x, h in zip(cols, ("Test Name", "Result", "Flag", "Unit", "Bio. Ref. Interval"), strict=True):
            c.drawString(x, d.y, h)
        c.line(LEFT, d.y - 4, RIGHT, d.y - 4)
        d.y -= 16
        for row in section.rows:
            d.ensure(16)
            c.setFont("Helvetica", 9)
            c.drawString(cols[0], d.y, row.printed_name)
            c.setFont("Helvetica-Bold" if row.flag else "Helvetica", 9)
            c.drawString(cols[1], d.y, row.printed_value)
            c.drawString(cols[2], d.y, row.flag)
            c.setFont("Helvetica", 9)
            c.drawString(cols[3], d.y, row.printed_unit)
            c.drawString(cols[4], d.y, row.printed_range)
            d.record(row, d.y)
            d.y -= 15
        d.y -= 10


def _layout_boxed(d: _Doc) -> None:
    cols = (LEFT, 230, 320, 400, RIGHT)
    c = d.c
    for section in d.spec.sections:
        d.ensure(70)
        c.setFont("Helvetica-Bold", 10)
        c.drawString(LEFT, d.y, section.title)
        d.y -= 10
        c.setFillColor(LIGHT)
        c.rect(LEFT, d.y - 14, RIGHT - LEFT, 16, stroke=1, fill=1)
        c.setFillColor(black)
        c.setFont("Helvetica-Bold", 8.5)
        for x, h in zip(cols[:4], ("Investigation", "Observed Value", "Units", "Reference Range"), strict=True):
            c.drawString(x + 4, d.y - 9, h)
        d.y -= 14
        for row in section.rows:
            if d.y - 16 < BOTTOM:
                d.new_page()
            c.rect(LEFT, d.y - 16, RIGHT - LEFT, 16, stroke=1, fill=0)
            for x in cols[1:-1]:
                c.line(x, d.y, x, d.y - 16)
            base = d.y - 11.5
            c.setFont("Helvetica", 9)
            c.drawString(cols[0] + 4, base, row.printed_name)
            value = f"{row.printed_value} ({row.flag})" if row.flag else row.printed_value
            c.setFont("Helvetica-Bold" if row.flag else "Helvetica", 9)
            c.drawString(cols[1] + 4, base, value)
            c.setFont("Helvetica", 9)
            c.drawString(cols[2] + 4, base, row.printed_unit)
            c.drawString(cols[3] + 4, base, row.printed_range)
            d.record(row, base)
            d.y -= 16
        d.y -= 18


def _layout_leaders(d: _Doc) -> None:
    c = d.c
    value_x, unit_x, range_x = 300, 350, 430
    for section in d.spec.sections:
        d.ensure(40)
        c.setFont("Helvetica-Bold", 10)
        c.drawString(LEFT, d.y, section.title)
        c.line(LEFT, d.y - 3, LEFT + stringWidth(section.title, "Helvetica-Bold", 10), d.y - 3)
        d.y -= 18
        for row in section.rows:
            d.ensure(14)
            c.setFont("Helvetica", 9)
            c.drawString(LEFT + 8, d.y, row.printed_name)
            start = LEFT + 12 + stringWidth(row.printed_name, "Helvetica", 9)
            dots = int((value_x - 8 - start) / stringWidth(".", "Helvetica", 9))
            c.setFillColor(GREY)
            c.drawString(start, d.y, "." * max(dots, 0))
            c.setFillColor(black)
            c.setFont("Helvetica-Bold" if row.flag else "Helvetica", 9)
            c.drawRightString(unit_x - 8, d.y, row.printed_value + (f" {row.flag}" if row.flag else ""))
            c.setFont("Helvetica", 9)
            c.drawString(unit_x, d.y, row.printed_unit)
            if row.printed_range:
                c.drawString(range_x, d.y, f"[{row.printed_range}]")
            d.record(row, d.y)
            d.y -= 14
        d.y -= 10


LAYOUTS = {"table": _layout_table, "boxed": _layout_boxed, "leaders": _layout_leaders}


def render_pdf(spec: ReportSpec, path: Path) -> int:
    """Write the PDF and return the number of pages. Row bounding boxes are filled in on `spec`."""
    d = _Doc(spec, path)
    d.new_page()
    LAYOUTS[spec.lab.layout](d)
    return d.finish()
