"""Render a ReportSpec to PDF with one of three layouts, recording each row's bounding box."""

from __future__ import annotations

import io
import random
from pathlib import Path

from reportlab.graphics.barcode.code128 import Code128
from reportlab.lib.colors import Color, HexColor, black, white
from reportlab.lib.pagesizes import A4
from reportlab.pdfbase.pdfmetrics import stringWidth
from reportlab.pdfgen.canvas import Canvas

from tools.synthetic.spec import ReportSpec, Row

W, H = A4
LEFT, RIGHT, TOP, BOTTOM = 40, W - 40, H - 40, 70
GREY = Color(0.55, 0.55, 0.55)
LIGHT = Color(0.92, 0.92, 0.92)
LIGHT_RULE = Color(0.75, 0.75, 0.75)
FOOTER = "Synthetic report generated by Nabz for software testing. Not a medical record."


class _Doc:
    def __init__(self, spec: ReportSpec, out: Path | io.BytesIO, total_pages: int | None = None):
        self.spec = spec
        self.c = Canvas(out if isinstance(out, io.BytesIO) else str(out), pagesize=A4)
        self.c.setTitle(f"{spec.lab.name} - {spec.package} - {spec.patient_name}")
        self.c.setAuthor(spec.lab.name)
        self.total = total_pages
        self.page = 0
        self.y = 0.0
        self.brand = HexColor(spec.lab.colour)
        self.rng = random.Random(spec.lab_no)

    # -- page furniture ---------------------------------------------------------------
    def logo(self, x: float, y: float, size: float) -> None:
        """A drawn mark with no text, so the lab name stays the first line a reader finds."""
        c = self.c
        c.saveState()
        c.setFillColor(self.brand)
        c.circle(x + size / 2, y + size / 2, size / 2, stroke=0, fill=1)
        c.setFillColor(white)
        arm = size * 0.16
        c.rect(x + size / 2 - arm / 2, y + size * 0.2, arm, size * 0.6, stroke=0, fill=1)
        c.rect(x + size * 0.2, y + size / 2 - arm / 2, size * 0.6, arm, stroke=0, fill=1)
        c.restoreState()

    def header(self) -> None:
        s, c = self.spec, self.c
        if self.page == 0:
            self.logo(LEFT, TOP - 32, 30)
            c.setFont("Helvetica-Bold", 16)
            c.setFillColor(self.brand)
            c.drawString(LEFT + 38, TOP - 12, s.lab.name)
            c.setFillColor(black)
            c.setFont("Helvetica-Oblique", 7.5)
            c.drawString(LEFT + 38, TOP - 22, s.lab.tagline)
            c.setFont("Helvetica", 7.5)
            parts = (s.lab.address, f"Ph: {s.lab.phone}" if s.lab.phone else "", s.lab.email)
            c.drawString(LEFT + 38, TOP - 31, "  |  ".join(x for x in parts if x))
            barcode = Code128(s.lab_no, barHeight=22, barWidth=0.9, humanReadable=False)
            barcode.drawOn(c, RIGHT - barcode.width, TOP - 30)
            c.setStrokeColor(self.brand)
            c.setLineWidth(1.4)
            c.line(LEFT, TOP - 40, RIGHT, TOP - 40)
            c.setStrokeColor(black)
            c.setLineWidth(1)

            p = s.persona
            when = s.collected_at.strftime("%d/%m/%Y")
            hh, mm = self.rng.randint(7, 10), self.rng.choice([12, 20, 27, 34, 41, 48, 55])
            reported = f"{self.rng.randint(15, 19)}:{self.rng.choice(['05', '20', '35', '50'])}"
            fields = [
                ("Patient Name", s.patient_name, "Lab No.", s.lab_no),
                ("Age / Sex", f"{p.age} Y / {p.sex.title()}", "Registered", f"{when} {hh:02d}:{mm - 6:02d}"),
                ("Ref. By", s.lab.referrer, "Collected", f"{when} {hh:02d}:{mm:02d}"),
                ("Sample At", s.lab.collection_point, "Reported", f"{when} {reported}"),
            ]
            top = TOP - 48
            c.setStrokeColor(LIGHT_RULE)
            c.roundRect(LEFT, top - 13 * len(fields) - 4, RIGHT - LEFT, 13 * len(fields) + 6, 3, stroke=1, fill=0)
            c.setStrokeColor(black)
            y = top - 10
            for a, av, b, bv in fields:
                c.setFont("Helvetica-Bold", 8.5)
                c.drawString(LEFT + 6, y, f"{a}:")
                c.drawString(W / 2 + 20, y, f"{b}:")
                c.setFont("Helvetica", 8.5)
                c.drawString(LEFT + 80, y, av)
                c.drawString(W / 2 + 90, y, bv)
                y -= 13
            c.setFont("Helvetica-Bold", 11)
            c.drawCentredString(W / 2, y - 12, s.package.upper())
            self.y = y - 34
        else:
            self.logo(LEFT, TOP - 12, 12)
            c.setFont("Helvetica-Bold", 10)
            c.drawString(LEFT + 16, TOP - 4, s.lab.name)
            c.setFont("Helvetica", 8.5)
            c.drawRightString(RIGHT, TOP - 4, f"{s.patient_name} · Lab No. {s.lab_no}")
            c.line(LEFT, TOP - 10, RIGHT, TOP - 10)
            self.y = TOP - 30

    def footer(self) -> None:
        c = self.c
        c.setStrokeColor(self.brand)
        c.line(LEFT, 52, RIGHT, 52)
        c.setStrokeColor(black)
        c.setFont("Helvetica", 7)
        c.setFillColor(GREY)
        c.drawString(LEFT, 43, "Results relate only to the sample tested. Please correlate clinically.")
        page = f"Page {self.page + 1} of {self.total}" if self.total else f"Page {self.page + 1}"
        c.drawRightString(RIGHT, 43, page)
        c.setFont("Helvetica-Oblique", 6)
        c.drawString(LEFT, 33, FOOTER)
        c.setFillColor(black)

    def new_page(self) -> None:
        if self.page or self.y:
            self.footer()
            self.c.showPage()
            self.page += 1
        self.header()

    def ensure(self, height: float) -> None:
        if self.y - height < BOTTOM:
            self.new_page()

    def record(self, row: Row, y: float, x0: float = LEFT, x1: float = RIGHT) -> None:
        row.page = self.page
        row.bbox = (round(x0, 1), round(H - (y + 9), 1), round(x1, 1), round(H - (y - 3), 1))

    def signature(self, x: float, y: float, width: float, seed: str) -> None:
        """An ink scribble: a few joined curves, the same for a signatory on every report."""
        c, rng = self.c, random.Random(seed)
        c.saveState()
        c.setStrokeColor(HexColor("#1b2a6b"))
        c.setLineWidth(0.9)
        path = c.beginPath()
        px, py = x, y
        path.moveTo(px, py)
        for _ in range(5):
            nx = px + width / 5
            path.curveTo(px + rng.uniform(2, 8), py + rng.uniform(6, 14), nx - rng.uniform(2, 8),
                         py - rng.uniform(4, 10), nx, py + rng.uniform(-3, 3))
            px = nx
        c.drawPath(path, stroke=1, fill=0)
        c.restoreState()

    def finish(self) -> int:
        c = self.c
        self.ensure(90)
        c.setFont("Helvetica", 8.5)
        c.drawCentredString(W / 2, self.y - 6, "*** End of Report ***")
        base = self.y - 58
        if self.spec.lab.technologist:
            self.signature(LEFT + 10, base + 14, 70, self.spec.lab.technologist)
            c.setFont("Helvetica-Bold", 8.5)
            c.drawString(LEFT, base, self.spec.lab.technologist)
            c.setFont("Helvetica", 7.5)
            c.drawString(LEFT, base - 10, "Lab Technologist")
        self.signature(RIGHT - 110, base + 14, 90, self.spec.lab.doctor)
        c.setFont("Helvetica-Bold", 8.5)
        c.drawRightString(RIGHT, base, f"{self.spec.lab.doctor}, MD (Pathology)")
        c.setFont("Helvetica", 7.5)
        c.drawRightString(RIGHT, base - 10, "Consultant Pathologist")
        self.footer()
        c.save()
        return self.page + 1


def _layout_table(d: _Doc) -> None:
    cols = (LEFT + 4, 250, 312, 340, 440)
    c = d.c
    for section in d.spec.sections:
        d.ensure(60)
        c.setFillColor(LIGHT)
        c.rect(LEFT, d.y - 4, RIGHT - LEFT, 15, stroke=0, fill=1)
        c.setFillColor(black)
        c.setFont("Helvetica-Bold", 9.5)
        c.drawString(LEFT + 4, d.y, section.title)
        d.y -= 18
        c.setFont("Helvetica-Bold", 8.5)
        for x, h in zip(cols, ("Test Name", "Result", "Flag", "Unit", "Bio. Ref. Interval"), strict=True):
            c.drawString(x, d.y, h)
        c.line(LEFT, d.y - 4, RIGHT, d.y - 4)
        d.y -= 16
        for row in section.rows:
            d.ensure(16)
            c.setFont("Helvetica", 9)
            c.drawString(cols[0], d.y, row.printed_name)
            c.setFont("Helvetica-Bold" if row.flag else "Helvetica", 9)
            c.drawString(cols[1], d.y, row.printed_value)
            c.drawString(cols[2], d.y, row.flag)
            c.setFont("Helvetica", 9)
            c.drawString(cols[3], d.y, row.printed_unit)
            c.drawString(cols[4], d.y, row.printed_range)
            d.record(row, d.y)
            d.y -= 15
        d.y -= 10


def _layout_boxed(d: _Doc) -> None:
    cols = (LEFT, 230, 320, 400, RIGHT)
    c = d.c
    for section in d.spec.sections:
        d.ensure(70)
        c.setFont("Helvetica-Bold", 10)
        c.drawString(LEFT, d.y, section.title)
        d.y -= 10
        c.setFillColor(LIGHT)
        c.rect(LEFT, d.y - 14, RIGHT - LEFT, 16, stroke=1, fill=1)
        c.setFillColor(black)
        c.setFont("Helvetica-Bold", 8.5)
        for x, h in zip(cols[:4], ("Investigation", "Observed Value", "Units", "Reference Range"), strict=True):
            c.drawString(x + 4, d.y - 9, h)
        d.y -= 14
        for row in section.rows:
            if d.y - 16 < BOTTOM:
                d.new_page()
            c.rect(LEFT, d.y - 16, RIGHT - LEFT, 16, stroke=1, fill=0)
            for x in cols[1:-1]:
                c.line(x, d.y, x, d.y - 16)
            base = d.y - 11.5
            c.setFont("Helvetica", 9)
            c.drawString(cols[0] + 4, base, row.printed_name)
            value = f"{row.printed_value} ({row.flag})" if row.flag else row.printed_value
            c.setFont("Helvetica-Bold" if row.flag else "Helvetica", 9)
            c.drawString(cols[1] + 4, base, value)
            c.setFont("Helvetica", 9)
            c.drawString(cols[2] + 4, base, row.printed_unit)
            c.drawString(cols[3] + 4, base, row.printed_range)
            d.record(row, base)
            d.y -= 16
        d.y -= 18


def _layout_leaders(d: _Doc) -> None:
    c = d.c
    value_x, unit_x, range_x = 300, 350, 430
    for section in d.spec.sections:
        d.ensure(40)
        c.setFont("Helvetica-Bold", 10)
        c.drawString(LEFT, d.y, section.title)
        c.line(LEFT, d.y - 3, LEFT + stringWidth(section.title, "Helvetica-Bold", 10), d.y - 3)
        d.y -= 18
        for row in section.rows:
            d.ensure(14)
            c.setFont("Helvetica", 9)
            c.drawString(LEFT + 8, d.y, row.printed_name)
            start = LEFT + 12 + stringWidth(row.printed_name, "Helvetica", 9)
            dots = int((value_x - 8 - start) / stringWidth(".", "Helvetica", 9))
            c.setFillColor(GREY)
            c.drawString(start, d.y, "." * max(dots, 0))
            c.setFillColor(black)
            c.setFont("Helvetica-Bold" if row.flag else "Helvetica", 9)
            c.drawRightString(unit_x - 8, d.y, row.printed_value + (f" {row.flag}" if row.flag else ""))
            c.setFont("Helvetica", 9)
            c.drawString(unit_x, d.y, row.printed_unit)
            if row.printed_range:
                c.drawString(range_x, d.y, f"[{row.printed_range}]")
            d.record(row, d.y)
            d.y -= 14
        d.y -= 10


LAYOUTS = {"table": _layout_table, "boxed": _layout_boxed, "leaders": _layout_leaders}


def _render(spec: ReportSpec, out: Path | io.BytesIO, total: int | None) -> int:
    d = _Doc(spec, out, total)
    d.new_page()
    LAYOUTS[spec.lab.layout](d)
    return d.finish()


def render_pdf(spec: ReportSpec, path: Path) -> int:
    """Write the PDF and return the number of pages. Row bounding boxes are filled in on `spec`.
    A first pass counts the pages so each footer can say "Page 1 of 2"."""
    total = _render(spec, io.BytesIO(), None)
    return _render(spec, path, total)
