"""processing job args

Revision ID: deb0c8c5362a
Revises: 8645bb7303a0
Create Date: 2026-09-29 18:17:25.406191
"""
from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'deb0c8c5362a'
down_revision: str | None = '8645bb7303a0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('processing_job', sa.Column('args', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('processing_job', 'args')
    # ### end Alembic commands ###
