"""observation raw flag and section

Revision ID: f45d9a1f8a92
Revises: 5570cec69006
Create Date: 2026-09-27 05:39:02.458544
"""
from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op


revision: str = 'f45d9a1f8a92'
down_revision: str | None = '5570cec69006'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('observation', sa.Column('raw_flag', sa.Text(), nullable=True))
    op.add_column('observation', sa.Column('section', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('observation', 'section')
    op.drop_column('observation', 'raw_flag')
    # ### end Alembic commands ###
