"""observation match and ocr confidence

Revision ID: 49e27441af0f
Revises: f45d9a1f8a92
Create Date: 2026-09-27 14:07:15.955640
"""
from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '49e27441af0f'
down_revision: str | None = 'f45d9a1f8a92'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('observation', sa.Column('ocr_confidence', sa.REAL(), nullable=True))
    op.add_column('observation', sa.Column('match_score', sa.REAL(), nullable=True))
    op.add_column('observation', sa.Column('match_method', sa.Text(), nullable=True))
    op.add_column('observation', sa.Column('match_candidates', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('observation', 'match_candidates')
    op.drop_column('observation', 'match_method')
    op.drop_column('observation', 'match_score')
    op.drop_column('observation', 'ocr_confidence')
    # ### end Alembic commands ###
