"""observation analysis and trend insight detail

Revision ID: 8645bb7303a0
Revises: 49e27441af0f
Create Date: 2026-09-28 14:28:30.367528
"""
from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '8645bb7303a0'
down_revision: str | None = '49e27441af0f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('observation', sa.Column('analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('trend_insight', sa.Column('last_observation_id', sa.UUID(), nullable=True))
    op.add_column('trend_insight', sa.Column('direction', sa.Text(), nullable=True))
    op.add_column('trend_insight', sa.Column('confirmed', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.create_foreign_key(op.f('fk_trend_insight_last_observation_id_observation'), 'trend_insight', 'observation', ['last_observation_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_trend_insight_last_observation_id_observation'), 'trend_insight', type_='foreignkey')
    op.drop_column('trend_insight', 'confirmed')
    op.drop_column('trend_insight', 'direction')
    op.drop_column('trend_insight', 'last_observation_id')
    op.drop_column('observation', 'analysis')
    # ### end Alembic commands ###
