"""accounts sessions tokens

Revision ID: cac5f9c0909e
Revises: deb0c8c5362a
Create Date: 2026-09-30 04:30:57.114529
"""
from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op


revision: str = 'cac5f9c0909e'
down_revision: str | None = 'deb0c8c5362a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # New roles (docs/12 §2). ADD VALUE can't be used in the transaction that adds it, so it runs on its own.
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE user_role ADD VALUE IF NOT EXISTS 'clinician'")
        op.execute("ALTER TYPE user_role ADD VALUE IF NOT EXISTS 'reviewer'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_token',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('purpose', sa.Enum('verify_email', 'reset_password', name='token_purpose'), nullable=False),
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], name=op.f('fk_auth_token_user_id_app_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auth_token')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_auth_token_token_hash'))
    )
    op.create_index(op.f('ix_auth_token_user_id'), 'auth_token', ['user_id'], unique=False)
    op.create_table('user_session',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('csrf_token', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], name=op.f('fk_user_session_user_id_app_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_session')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_user_session_token_hash'))
    )
    op.create_index(op.f('ix_user_session_user_id'), 'user_session', ['user_id'], unique=False)
    op.add_column('app_user', sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('app_user', sa.Column('totp_secret_enc', sa.Text(), nullable=True))
    op.add_column('app_user', sa.Column('totp_enabled_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('app_user', sa.Column('failed_logins', sa.SmallInteger(), server_default='0', nullable=False))
    op.add_column('app_user', sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_user', 'locked_until')
    op.drop_column('app_user', 'failed_logins')
    op.drop_column('app_user', 'totp_enabled_at')
    op.drop_column('app_user', 'totp_secret_enc')
    op.drop_column('app_user', 'email_verified_at')
    op.drop_index(op.f('ix_user_session_user_id'), table_name='user_session')
    op.drop_table('user_session')
    op.drop_index(op.f('ix_auth_token_user_id'), table_name='auth_token')
    op.drop_table('auth_token')
    sa.Enum(name='token_purpose').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
    # PostgreSQL can't drop enum values: 'clinician' and 'reviewer' stay in user_role (unused).
