"""initial schema

Revision ID: 5570cec69006
Revises: 
Create Date: 2026-09-26 13:49:32.037746
"""
from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '5570cec69006'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


EXTENSIONS = ("vector", "pg_trgm", "pgcrypto", "citext")
ENUMS = ("lang", "user_role", "sex", "relationship", "consent_purpose", "report_status",
         "safety_status", "job_stage", "job_status", "obs_status")


def upgrade() -> None:
    for ext in EXTENSIONS:
        op.execute(f"CREATE EXTENSION IF NOT EXISTS {ext}")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', postgresql.CITEXT(), nullable=False),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('preferred_language', sa.Enum('en', 'hi', 'or', name='lang'), nullable=False),
    sa.Column('role', sa.Enum('user', 'admin', name='user_role'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_app_user')),
    sa.UniqueConstraint('email', name=op.f('uq_app_user_email'))
    )
    op.create_table('kb_document',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('source_org', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('license', sa.Text(), nullable=False),
    sa.Column('language', sa.Enum('en', 'hi', 'or', name='lang'), nullable=False),
    sa.Column('retrieved_at', sa.Date(), nullable=True),
    sa.Column('checksum', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kb_document'))
    )
    op.create_table('organ_system',
    sa.Column('id', sa.SmallInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('name_en', sa.Text(), nullable=False),
    sa.Column('name_hi', sa.Text(), nullable=False),
    sa.Column('name_or', sa.Text(), nullable=False),
    sa.Column('mesh_ids', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('translations_reviewed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organ_system')),
    sa.UniqueConstraint('code', name=op.f('uq_organ_system_code'))
    )
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['actor_user_id'], ['app_user.id'], name=op.f('fk_audit_log_actor_user_id_app_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_index(op.f('ix_audit_log_actor_user_id'), 'audit_log', ['actor_user_id'], unique=False)
    op.create_table('lab_test',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('loinc_code', sa.Text(), nullable=False),
    sa.Column('canonical_name', sa.Text(), nullable=False),
    sa.Column('short_name', sa.Text(), nullable=False),
    sa.Column('panel', sa.Text(), nullable=False),
    sa.Column('aliases', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('organ_system_id', sa.SmallInteger(), nullable=False),
    sa.Column('canonical_unit', sa.Text(), nullable=False),
    sa.Column('decimals', sa.SmallInteger(), nullable=False),
    sa.Column('plausible_min', sa.Numeric(), nullable=False),
    sa.Column('plausible_max', sa.Numeric(), nullable=False),
    sa.Column('cv_within_subject', sa.REAL(), nullable=True),
    sa.Column('cv_analytical', sa.REAL(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['organ_system_id'], ['organ_system.id'], name=op.f('fk_lab_test_organ_system_id_organ_system')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lab_test')),
    sa.UniqueConstraint('code', name=op.f('uq_lab_test_code')),
    sa.UniqueConstraint('loinc_code', name=op.f('uq_lab_test_loinc_code'))
    )
    op.create_index(op.f('ix_lab_test_organ_system_id'), 'lab_test', ['organ_system_id'], unique=False)
    op.create_index(op.f('ix_lab_test_panel'), 'lab_test', ['panel'], unique=False)
    op.create_table('profile',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('sex', sa.Enum('female', 'male', 'other', 'unknown', name='sex'), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('relationship', sa.Enum('self', 'parent', 'child', 'spouse', 'other', name='relationship'), nullable=False),
    sa.Column('preferred_language', sa.Enum('en', 'hi', 'or', name='lang'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['app_user.id'], name=op.f('fk_profile_owner_user_id_app_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profile'))
    )
    op.create_index(op.f('ix_profile_owner_user_id'), 'profile', ['owner_user_id'], unique=False)
    op.create_table('consent',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('purpose', sa.Enum('processing', 'external_ai', 'voice', 'research', name='consent_purpose'), nullable=False),
    sa.Column('policy_version', sa.Text(), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], name=op.f('fk_consent_profile_id_profile'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], name=op.f('fk_consent_user_id_app_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consent'))
    )
    op.create_index(op.f('ix_consent_profile_id'), 'consent', ['profile_id'], unique=False)
    op.create_table('critical_limit',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('low', sa.Numeric(), nullable=True),
    sa.Column('high', sa.Numeric(), nullable=True),
    sa.Column('message_key', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('reviewed_by', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['test_id'], ['lab_test.id'], name=op.f('fk_critical_limit_test_id_lab_test'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_critical_limit')),
    sa.UniqueConstraint('test_id', name=op.f('uq_critical_limit_test_id'))
    )
    op.create_table('kb_chunk',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=True),
    sa.Column('chunk_index', sa.SmallInteger(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('language', sa.Enum('en', 'hi', 'or', name='lang'), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['kb_document.id'], name=op.f('fk_kb_chunk_document_id_kb_document'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_id'], ['lab_test.id'], name=op.f('fk_kb_chunk_test_id_lab_test')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kb_chunk'))
    )
    op.create_index(op.f('ix_kb_chunk_document_id'), 'kb_chunk', ['document_id'], unique=False)
    op.create_index('ix_kb_chunk_embedding_hnsw', 'kb_chunk', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index(op.f('ix_kb_chunk_test_id'), 'kb_chunk', ['test_id'], unique=False)
    op.create_table('population_percentile',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('sex', sa.Enum('female', 'male', 'other', 'unknown', name='sex'), nullable=False),
    sa.Column('age_band', postgresql.INT4RANGE(), nullable=False),
    sa.Column('p05', sa.Numeric(), nullable=False),
    sa.Column('p25', sa.Numeric(), nullable=False),
    sa.Column('p50', sa.Numeric(), nullable=False),
    sa.Column('p75', sa.Numeric(), nullable=False),
    sa.Column('p95', sa.Numeric(), nullable=False),
    sa.Column('n', sa.Integer(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['test_id'], ['lab_test.id'], name=op.f('fk_population_percentile_test_id_lab_test'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_population_percentile'))
    )
    op.create_index(op.f('ix_population_percentile_test_id'), 'population_percentile', ['test_id'], unique=False)
    op.create_table('reference_range',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('sex', sa.Enum('female', 'male', 'other', 'unknown', name='sex'), nullable=False),
    sa.Column('age_min', sa.SmallInteger(), nullable=False),
    sa.Column('age_max', sa.SmallInteger(), nullable=False),
    sa.Column('low', sa.Numeric(), nullable=True),
    sa.Column('high', sa.Numeric(), nullable=True),
    sa.Column('source', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['test_id'], ['lab_test.id'], name=op.f('fk_reference_range_test_id_lab_test'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reference_range'))
    )
    op.create_index(op.f('ix_reference_range_test_id'), 'reference_range', ['test_id'], unique=False)
    op.create_table('report',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('lab_name', sa.Text(), nullable=True),
    sa.Column('collected_at', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('uploaded', 'rejected', 'queued', 'processing', 'needs_review', 'verified', 'analysing', 'explaining', 'explained', 'failed', 'deleted', name='report_status'), nullable=False),
    sa.Column('source_sha256', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], name=op.f('fk_report_profile_id_profile'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['app_user.id'], name=op.f('fk_report_uploaded_by_app_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_report'))
    )
    op.create_index('ix_report_profile_collected', 'report', ['profile_id', sa.literal_column('collected_at DESC')], unique=False)
    op.create_index('uq_report_profile_source', 'report', ['profile_id', 'source_sha256'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('trend_insight',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('n_points', sa.SmallInteger(), nullable=False),
    sa.Column('slope_per_year', sa.Numeric(), nullable=True),
    sa.Column('rcv_significant', sa.Boolean(), nullable=True),
    sa.Column('projected_crossing', sa.Date(), nullable=True),
    sa.Column('percentile', sa.REAL(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], name=op.f('fk_trend_insight_profile_id_profile'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_id'], ['lab_test.id'], name=op.f('fk_trend_insight_test_id_lab_test')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trend_insight')),
    sa.UniqueConstraint('profile_id', 'test_id', name='uq_trend_insight_profile_test')
    )
    op.create_table('unit_conversion',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('from_unit', sa.Text(), nullable=False),
    sa.Column('factor', sa.Numeric(), nullable=False),
    sa.Column('offset', sa.Numeric(), nullable=False),
    sa.ForeignKeyConstraint(['test_id'], ['lab_test.id'], name=op.f('fk_unit_conversion_test_id_lab_test'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_unit_conversion')),
    sa.UniqueConstraint('test_id', 'from_unit', name='uq_unit_conversion_test_from')
    )
    op.create_index(op.f('ix_unit_conversion_test_id'), 'unit_conversion', ['test_id'], unique=False)
    op.create_table('explanation',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('language', sa.Enum('en', 'hi', 'or', name='lang'), nullable=False),
    sa.Column('model_id', sa.Text(), nullable=False),
    sa.Column('prompt_version', sa.Text(), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('safety_status', sa.Enum('passed', 'fallback', 'blocked', name='safety_status'), nullable=False),
    sa.Column('audio_key', sa.Text(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['report.id'], name=op.f('fk_explanation_report_id_report'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_explanation'))
    )
    op.create_index(op.f('ix_explanation_report_id'), 'explanation', ['report_id'], unique=False)
    op.create_table('processing_job',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('stage', sa.Enum('extract', 'analyse', 'explain', 'narrate', name='job_stage'), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'succeeded', 'failed', name='job_status'), nullable=False),
    sa.Column('attempts', sa.SmallInteger(), nullable=False),
    sa.Column('run_after', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_by', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['report.id'], name=op.f('fk_processing_job_report_id_report'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_processing_job'))
    )
    op.create_index('ix_processing_job_queued', 'processing_job', ['run_after'], unique=False, postgresql_where=sa.text("status = 'queued'"))
    op.create_index(op.f('ix_processing_job_report_id'), 'processing_job', ['report_id'], unique=False)
    op.create_table('report_file',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('storage_key', sa.Text(), nullable=False),
    sa.Column('mime_type', sa.Text(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.Text(), nullable=False),
    sa.Column('quality_score', sa.REAL(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['report.id'], name=op.f('fk_report_file_report_id_report'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_report_file'))
    )
    op.create_index(op.f('ix_report_file_report_id'), 'report_file', ['report_id'], unique=False)
    op.create_table('share_link',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.id'], name=op.f('fk_share_link_created_by_app_user'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_id'], ['report.id'], name=op.f('fk_share_link_report_id_report'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_share_link')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_share_link_token_hash'))
    )
    op.create_index(op.f('ix_share_link_report_id'), 'share_link', ['report_id'], unique=False)
    op.create_table('explanation_citation',
    sa.Column('explanation_id', sa.UUID(), nullable=False),
    sa.Column('kb_chunk_id', sa.UUID(), nullable=False),
    sa.Column('rank', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['explanation_id'], ['explanation.id'], name=op.f('fk_explanation_citation_explanation_id_explanation'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['kb_chunk_id'], ['kb_chunk.id'], name=op.f('fk_explanation_citation_kb_chunk_id_kb_chunk'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('explanation_id', 'kb_chunk_id', name=op.f('pk_explanation_citation'))
    )
    op.create_table('feedback',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('explanation_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('rating', sa.SmallInteger(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['explanation_id'], ['explanation.id'], name=op.f('fk_feedback_explanation_id_explanation'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], name=op.f('fk_feedback_user_id_app_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feedback'))
    )
    op.create_index(op.f('ix_feedback_explanation_id'), 'feedback', ['explanation_id'], unique=False)
    op.create_table('report_page',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('report_file_id', sa.UUID(), nullable=False),
    sa.Column('page_no', sa.SmallInteger(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('ocr', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['report_file_id'], ['report_file.id'], name=op.f('fk_report_page_report_file_id_report_file'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_report_page'))
    )
    op.create_index(op.f('ix_report_page_report_file_id'), 'report_page', ['report_file_id'], unique=False)
    op.create_table('observation',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('report_page_id', sa.UUID(), nullable=True),
    sa.Column('test_id', sa.Integer(), nullable=True),
    sa.Column('raw_name', sa.Text(), nullable=True),
    sa.Column('raw_value', sa.Text(), nullable=True),
    sa.Column('raw_unit', sa.Text(), nullable=True),
    sa.Column('raw_range', sa.Text(), nullable=True),
    sa.Column('value_num', sa.Numeric(), nullable=True),
    sa.Column('unit', sa.Text(), nullable=True),
    sa.Column('ref_low', sa.Numeric(), nullable=True),
    sa.Column('ref_high', sa.Numeric(), nullable=True),
    sa.Column('ref_source', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('low', 'normal', 'high', 'critical_low', 'critical_high', 'unknown', name='obs_status'), nullable=False),
    sa.Column('bbox', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence', sa.REAL(), nullable=False),
    sa.Column('edited', sa.Boolean(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['report.id'], name=op.f('fk_observation_report_id_report'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_page_id'], ['report_page.id'], name=op.f('fk_observation_report_page_id_report_page'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['test_id'], ['lab_test.id'], name=op.f('fk_observation_test_id_lab_test')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_observation'))
    )
    op.create_index(op.f('ix_observation_report_id'), 'observation', ['report_id'], unique=False)
    op.create_index(op.f('ix_observation_test_id'), 'observation', ['test_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_observation_test_id'), table_name='observation')
    op.drop_index(op.f('ix_observation_report_id'), table_name='observation')
    op.drop_table('observation')
    op.drop_index(op.f('ix_report_page_report_file_id'), table_name='report_page')
    op.drop_table('report_page')
    op.drop_index(op.f('ix_feedback_explanation_id'), table_name='feedback')
    op.drop_table('feedback')
    op.drop_table('explanation_citation')
    op.drop_index(op.f('ix_share_link_report_id'), table_name='share_link')
    op.drop_table('share_link')
    op.drop_index(op.f('ix_report_file_report_id'), table_name='report_file')
    op.drop_table('report_file')
    op.drop_index(op.f('ix_processing_job_report_id'), table_name='processing_job')
    op.drop_index('ix_processing_job_queued', table_name='processing_job', postgresql_where=sa.text("status = 'queued'"))
    op.drop_table('processing_job')
    op.drop_index(op.f('ix_explanation_report_id'), table_name='explanation')
    op.drop_table('explanation')
    op.drop_index(op.f('ix_unit_conversion_test_id'), table_name='unit_conversion')
    op.drop_table('unit_conversion')
    op.drop_table('trend_insight')
    op.drop_index('uq_report_profile_source', table_name='report', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_report_profile_collected', table_name='report')
    op.drop_table('report')
    op.drop_index(op.f('ix_reference_range_test_id'), table_name='reference_range')
    op.drop_table('reference_range')
    op.drop_index(op.f('ix_population_percentile_test_id'), table_name='population_percentile')
    op.drop_table('population_percentile')
    op.drop_index(op.f('ix_kb_chunk_test_id'), table_name='kb_chunk')
    op.drop_index('ix_kb_chunk_embedding_hnsw', table_name='kb_chunk', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index(op.f('ix_kb_chunk_document_id'), table_name='kb_chunk')
    op.drop_table('kb_chunk')
    op.drop_table('critical_limit')
    op.drop_index(op.f('ix_consent_profile_id'), table_name='consent')
    op.drop_table('consent')
    op.drop_index(op.f('ix_profile_owner_user_id'), table_name='profile')
    op.drop_table('profile')
    op.drop_index(op.f('ix_lab_test_panel'), table_name='lab_test')
    op.drop_index(op.f('ix_lab_test_organ_system_id'), table_name='lab_test')
    op.drop_table('lab_test')
    op.drop_index(op.f('ix_audit_log_actor_user_id'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('organ_system')
    op.drop_table('kb_document')
    op.drop_table('app_user')
    # ### end Alembic commands ###
    for name in ENUMS:
        op.execute(f"DROP TYPE IF EXISTS {name}")
